### ISSUE TITLE
Problem with images convert to video. 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [shaynet10/puppeteer-video-recorder#4]
I run the following script and it does generate correct number of frames and txt file with list of frames. 
BUT during converting to video tries to use wrong path

```
root@youstreamer:~/recorder# node yo.js 
/root/recorder/node_modules/puppeteer-video-recorder/index.js:45
            if (error) throw new Error(error);
                       ^

Error: Error: Command failed: ffmpeg -f concat -safe 0 -i kek/images.txt -framerate 60 kek/1622394592543.webm
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[concat @ 0x1fcc440] Impossible to open 'kek/kek/images/1622387952383.jpg'
kek/images.txt: No such file or directory

    at /root/recorder/node_modules/puppeteer-video-recorder/index.js:45:30
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```

```
const puppeteer = require('puppeteer');
const PuppeteerVideoRecorder = require('puppeteer-video-recorder');

const recorder = new PuppeteerVideoRecorder();

function delay(time) {
   return new Promise(function(resolve) {
       setTimeout(resolve, time)
   });
}
(async () => {

  const browser = await puppeteer.launch({args: ['--disable-infobars','--autoplay-policy=no-user-gesture-required', '--start-maximized', '--no-sandbox', '--disable-gpu', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--start-fullscreen', '--window-size=1280,720', '--window-position=0,0', '--user-data-dir=/test', '--autoplay-policy=no-user-gesture-required', '--kiosk', '--hide-scrollbars']});
  const page = await browser.newPage();
  await recorder.init(page, './kek');



  await page.goto('https://meeting.youstreamer.com/webinar/?roomId=serv28b3f5c18c97b0259c53a7eb2132638e6&already=true&displayName=streamer');
  await recorder.start();

  const searchButtonNodeSelector = ".join-button";
  await page.click(searchButtonNodeSelector);
  await delay(10000);

  await page.screenshot({path: 'buddy-screenshot.png'});
  await recorder.stop();

  await delay(3000);

  await browser.close();
})();
```

**Comment by shaynet10** [comment]
Hi Alexander,
It is great to see you are using my package.
It looks like there is an issue with your default / relative output video path.

By default the output folder for the created video is set by this line:

await recorder.init(page, videosPath);

So by default what you send as videosPath
Is where the output video will be created.

Ensure, that you have permissions for creating new files and/or folders, in the videos output folder. It's also worthy to see your file system is not full there (from the error it looks like a simple text file wasn't created).

If for some reason, the ffmpeg decides to write you videos to somewhere else and you want to control directly the ffmpeg command, 
you can see my file:
https://github.com/shaynet10/puppeteer-video-recorder/blob/main/index.js

And see there, 
createVideo

You can override it and change there the default ffmpeg command, to whatever works for you.

Alternatively, you can decide 
not to use the stop command.

Since all it does is:

await this.screenshots.stop();    	
await this.createVideo();

And you can run these 2 commands with something like:
await recorder.screenshots.stop();    	
await recorder.createVideo(YourFFmpegCommand);
* Since you're using recorder as a reference to PuppeteerVideoRecorder object.

Hopefully that it was helpful to you.

**Comment by pashkasan** [comment]
same problem, can be fixed with   await recorder.init(page, __dirname + '/kek');

**Comment by shaynet10** [comment]
@pashkasan 
Thanks for noticing it.
In that case, this issue can be closed.
